apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: onos-deployment
spec:
  selector:
    matchLabels:
      app: onos
  replicas: 2 # tells deployment to run 5 pods matching the template
  template:
    metadata:
      labels:
        app: onos
    spec:
      containers:
      - name: onos
        image: onosproject/onos:2.2.0
        command: [ "/bin/bash" ]
        args: [ "-c", "sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && 
        apt update &&
        apt install sshpass -y &&
        echo [Config] Activate openflow app && 
        sshpass -p rocks ssh -q -p 8101 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null onos@127.0.0.1 "app activate org.onosproject.openflow" &&
        echo [Config] Activate openflow app &&
        sshpass -p rocks ssh -q -p 8101 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null onos@127.0.0.1 "app activate org.onosproject.fwd" &&
        sleep infinity" ]
        ports:
        - containerPort: 6653
        - containerPort: 8181

# http://localhost:8181/onos/ui
# username and password: onos/rocks
