apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: onos-deployment
spec:
  selector:
    matchLabels:
      app: onos
  replicas: 2 # tells deployment to run 5 pods matching the template
  template:
    metadata:
      labels:
        app: onos
    spec:
      containers:
      - name: onos
        image: onosproject/onos:1.13.9
        command: [ "/bin/bash" ]
        args: [ "-c", "echo [Config] Activate openflow app && app activate org.onosproject.openflow &&
        echo [Config] Activate openflow app && app activate org.onosproject.fwd && sleep infinity" ]
        ports:
        - containerPort: 6653
        - containerPort: 8181

# http://localhost:8181/onos/ui
# username and password: onos/rocks
